Repository wJoenn/artify, pull requests merged in 2023-03, with the labels that each got.

#20 Created Monument model
  app/models/monument.rb
  db/migrate/20230303114547_create_monuments.rb
  db/schema.rb
  test/models/monument_test.rb
Labels: waiting for review

#19 Created architect model
  app/models/architect.rb
  db/migrate/20230303094934_create_architects.rb
  db/schema.rb
  test/models/architect_test.rb
Labels: waiting for review

#25 Cloudinary setup completed
  Gemfile
  Gemfile.lock
  app/models/architect.rb
  app/models/monument.rb
  config/environments/development.rb
  config/environments/production.rb
  config/storage.yml
  db/migrate/20230303164439_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: waiting for review

#26 User model
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20230303221014_devise_create_users.rb
  db/migrate/20230304095201_add_details_to_users.rb
  db/schema.rb
Labels: requires changes

#23 initial pundit setup completed
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/policies/application_policy.rb
Labels: backlog

#29 Created history model and updated user and monument associations
  app/models/history.rb
  app/models/monument.rb
  app/models/user.rb
  db/migrate/20230304141223_create_histories.rb
  db/schema.rb
  test/models/history_test.rb
Labels: waiting for review

#31 Google cloud vision API
  .gitignore
  Gemfile
  Gemfile.lock
  db/seeds.rb
Labels: waiting for review

#33 Geocoder gem installed
  Gemfile
  Gemfile.lock
  app/models/monument.rb
  config/initializers/geocoder.rb
  db/seeds.rb
Labels: waiting for review

#32 updated existing controllers
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
Labels: waiting for review

#42 Table update
  app/models/architect.rb
  app/models/architect_monument.rb
  db/migrate/20230307112416_drop_architect_monuments.rb
  db/migrate/20230307112517_drop_architects.rb
  db/schema.rb
  test/models/architect_monument_test.rb
  test/models/architect_test.rb
Labels: requires changes

#43 Histories Controller
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/histories_controller.rb
  app/controllers/pages_controller.rb
  app/models/history.rb
  app/models/monument.rb
  app/models/user.rb
  app/policies/history_policy.rb
  app/views/histories/index.html.erb
  app/views/histories/show.html.erb
  app/views/pages/error.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
  db/migrate/20230306224927_add_city_and_country_to_monuments.rb
  db/migrate/20230306225112_remove_date_and_style_from_monuments.rb
  db/migrate/20230307182519_remove_coords_and_desc_from_histories.rb
  db/schema.rb
  db/seeds.rb
  resources/wikipedia_raw_data.rb
  test/controllers/histories_controller_test.rb
  test/policies/history_policy_test.rb
Labels: waiting for review

#44 Monuments-controller
  app/controllers/monuments_controller.rb
  app/policies/monument_policy.rb
  test/controllers/monuments_controller_test.rb
  test/policies/monument_policy_test.rb
Labels: waiting for review

#47 Created a geolocation stimulus controller
  app/javascript/controllers/geolocation_controller.js
  app/javascript/controllers/index.js
Labels: waiting for review

#50 Fixed Cloudinary photo max size problem
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/histories_controller.rb
  db/seeds.rb
Labels: waiting for review

#45 User html
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  db/migrate/20230307222759_remove_lng_and_lat_from_users.rb
  db/schema.rb
  db/seeds.rb
Labels: waiting for review, requires changes

#28 Homepage
  Gemfile.lock
  app/assets/images/Logo.png
  app/assets/images/background_image.jpeg
  app/assets/images/drag_card_placeholder.png
  app/assets/images/placeholder_image_map.png
  app/assets/stylesheets/pages/_home.scss
  app/views/pages/home.html.erb
Labels: requires changes

#52 Monuments index
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_containers.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_colors.scss
  app/controllers/monuments_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/map_controller.js
  app/views/layouts/application.html.erb
  app/views/monuments/index.html.erb
Labels: requires changes

#62 Navbar upgrade
  app/assets/stylesheets/components/_navbar.scss
  app/javascript/controllers/index.js
  app/javascript/controllers/window_events_controller.js
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
Labels: waiting for review

#61 Banner scroller simplified
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_navbar.scss
  app/javascript/controllers/banner_scroller_controller.js
  app/javascript/controllers/index.js
  app/views/shared/_banner.html.erb
Labels: waiting for review

#54 devise forms first draft
  app/assets/images/pink_avatar.svg
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_setup.scss
  app/javascript/controllers/index.js
  app/javascript/controllers/toggle_hidden_password_controller.js
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: requires changes

#63 Featured card new design
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/pages/home.html.erb
Labels: waiting for review

#65 Created a basic search form component
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_search_form.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/pages/home.html.erb
  app/views/shared/_banner.html.erb
  app/views/shared/_search_form.html.erb
Labels: waiting for review

#67 Photo bug fix
  app/controllers/histories_controller.rb
  app/models/monument.rb
  app/views/shared/_navbar.html.erb
  db/seeds.rb
Labels: bug, waiting for review

#71 search form working excluding city/name tags
  app/assets/stylesheets/components/_search_form.scss
  app/controllers/pages_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/search_form_controller.js
  app/views/pages/_banner.html.erb
  app/views/pages/_search_form.html.erb
  app/views/pages/_search_list.html.erb
  app/views/pages/_tutorial.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#70 Devise alerts
  app/assets/stylesheets/components/_flash.scss
  app/assets/stylesheets/components/_index.scss
  app/javascript/controllers/flashes_controller.js
  app/javascript/controllers/index.js
  app/views/devise/registrations/edit.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_flashes.html.erb
  config/locales/devise.en.yml
Labels: waiting for review

#80 Search form update for city and country
  app/assets/stylesheets/components/_banner.scss
  app/controllers/pages_controller.rb
  app/views/pages/components/_banner.html.erb
Labels: waiting for review

#83 Footer component
  app/assets/images/le_wagon_logo.png
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/pages/_home.scss
  app/controllers/pages_controller.rb
  app/views/layouts/application.html.erb
  app/views/shared/_footer.html.erb
Labels: waiting for review

#85 Loading screen added
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_loading.scss
  app/assets/stylesheets/pages/_home.scss
  app/javascript/controllers/camera_form_controller.js
  app/javascript/controllers/index.js
  app/views/pages/components/_banner.html.erb
  app/views/pages/components/_navbar.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#84 Changed monument selection to be different each day
  app/controllers/pages_controller.rb
  app/views/pages/components/_banner.html.erb
Labels: waiting for review

#87 Nearby section
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_nearby.scss
  app/assets/stylesheets/components/_search_form.scss
  app/controllers/pages_controller.rb
  app/models/monument.rb
  app/views/pages/components/_nearby.html.erb
  app/views/pages/components/_search_list.html.erb
  app/views/pages/home.html.erb
Labels: waiting for review

#81 index redone
  Gemfile.lock
  app/assets/images/eiffel-logo.png
  app/assets/images/logo.png
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/monuments/_index.scss
  app/controllers/monuments_controller.rb
  app/javascript/controllers/map_controller.js
  app/views/monuments/index.html.erb
  app/views/pages/home.html.erb
Labels: requires changes

#97 Added featured monument id to rails cache
  app/controllers/pages_controller.rb
Labels: waiting for review

#96 Error page created
  app/assets/images/not_found.png
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/pages/_error.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/histories_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/monuments/index.html.erb
  app/views/pages/error.html.erb
Labels: waiting for review

#99 guest_user helper created
  app/controllers/application_controller.rb
  app/controllers/histories_controller.rb
  app/models/user.rb
  db/seeds.rb
  lib/tasks/user.rake
Labels: waiting for review

#102 Monument duplicate bug fix
  app/controllers/histories_controller.rb
Labels: waiting for review

#106 Input text color on mobile fixed
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_search_form.scss
Labels: waiting for review

#107 Form no longer cropping on mobile
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/config/_setup.scss
  app/assets/stylesheets/pages/_home.scss
Labels: waiting for review

#112 Added policy to show history page is user are the same
  app/controllers/application_controller.rb
  app/models/user_context.rb
  app/policies/history_policy.rb
Labels: waiting for review

#120 Fixed issue for now
  app/models/monument.rb
Labels: waiting for review

#124 Featured monument fix
  app/controllers/pages_controller.rb
  app/models/monument.rb
  db/migrate/20230322103417_add_featured_date_to_monuments.rb
  db/schema.rb
Labels: waiting for review

#136 guest user deletion bug fixed
  app/controllers/application_controller.rb
Labels: waiting for review

#126 Increased some button sizes for better UX on mobile
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_nearby.scss
  app/assets/stylesheets/config/_animations.scss
  app/views/pages/components/_banner.html.erb
  config/environments/development.rb
Labels: waiting for review

#132 Added compression to user's photo
  app/controllers/histories_controller.rb
Labels: waiting for review

#135 Fix for same monuments with different names
  app/controllers/histories_controller.rb
Labels: waiting for review

#137 Created 2 Classes for wikipedia and google
  .rubocop.yml
  app/controllers/histories_controller.rb
  app/models/google_landmark.rb
  app/models/monument.rb
  app/models/wikipedia_data.rb
  app/views/pages/error.html.erb
Labels: waiting for review

#142 Fixed noscroll effect for mobiles
  app/assets/stylesheets/config/_setup.scss
  app/assets/stylesheets/pages/_home.scss
  app/javascript/controllers/camera_form_controller.js
  app/javascript/controllers/home_logo_controller.js
  app/javascript/controllers/tutorial_controller.js
  config/environments/development.rb
Labels: waiting for review

#138 Created Achievement model
  app/models/achievement.rb
  db/migrate/20230323123721_create_achievements.rb
  db/schema.rb
  test/models/achievement_test.rb
Labels: waiting for review

#140 Homepage nearby section
  app/assets/images/geolocation.svg
  app/assets/images/no_results.svg
  app/assets/stylesheets/pages/_home.scss
  app/controllers/monuments_controller.rb
  app/controllers/pages_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/nearby_controller.js
  app/javascript/controllers/search_form_controller.js
  app/models/monument.rb
  app/views/monuments/index.html.erb
  app/views/pages/components/_nearby.html.erb
  app/views/pages/components/_search_list.html.erb
  app/views/pages/components/_tutorial.html.erb
  app/views/shared/_monuments_scroller.html.erb
Labels: waiting for review

#123 User dashboard
  app/assets/images/badges_collection.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/users/_dashboard.scss
  app/assets/stylesheets/users/_index.scss
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/histories/index.html.erb
  app/views/pages/components/_navbar.html.erb
  app/views/users/components/_histories.html.erb
  app/views/users/dashboard.html.erb
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: waiting for review

#144 UserAchievement model created
  app/models/achievement.rb
  app/models/user.rb
  app/models/user_achievement.rb
  db/migrate/20230324125105_create_user_achievements.rb
  db/schema.rb
  test/models/user_achievement_test.rb
Labels: waiting for review

#145 Generated MonumentAchievement model
  app/models/achievement.rb
  app/models/monument.rb
  app/models/monument_achievement.rb
  db/migrate/20230324153108_create_monument_achievements.rb
  db/schema.rb
  test/models/monument_achievement_test.rb
Labels: waiting for review

#119 Monumentpage
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/monuments/_index.scss
  app/assets/stylesheets/monuments/_show.scss
  app/controllers/histories_controller.rb
  app/controllers/monuments_controller.rb
  app/javascript/controllers/glass_container_controller.js
  app/javascript/controllers/index.js
  app/views/histories/show.html.erb
  app/views/monuments/show.html.erb
  app/views/shared/_show.html.erb
Labels: requires changes

#158 Fixed featured monument, finally
  app/models/monument.rb
  config/environments/development.rb
Labels: waiting for review

#159 Changed redirect after user update to dashboard
  app/controllers/registrations_controller.rb
  config/routes.rb
Labels: waiting for review

#164 Achievement automatically added to monument
  app/controllers/histories_controller.rb
  app/models/monument.rb
  db/migrate/20230325195533_add_keyword_to_achievement.rb
  db/schema.rb
  db/seeds.rb
Labels: waiting for review

#157 Moved no result found in new partial
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/pages/_home.scss
  app/controllers/pages_controller.rb
  app/javascript/controllers/search_form_controller.js
  app/views/pages/components/_search_form.html.erb
  app/views/shared/_monuments_scroller.html.erb
  app/views/shared/_no_results.html.erb
  app/views/shared/_show.html.erb
  app/views/users/components/_histories.html.erb
Labels: waiting for review

#162 New histories now update or create UserAchievements
  app/assets/stylesheets/monuments/_show.scss
  app/controllers/histories_controller.rb
  app/models/user.rb
  app/models/user_achievement.rb
  db/migrate/20230324125105_create_user_achievements.rb
  db/schema.rb
  db/seeds.rb
Labels: waiting for review

#163 new branch index histories
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/histories/_index.scss
  app/controllers/histories_controller.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/search_histories_controller.js
  app/views/histories/components/_list.html.erb
  app/views/histories/index.html.erb
Labels: waiting for review

#171 Histories will now be updated instead of duplicated
  app/controllers/histories_controller.rb
  app/controllers/users_controller.rb
  app/models/photo_compressor.rb
Labels: waiting for review

#185 Removed pundit from project
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/histories_controller.rb
  app/controllers/monuments_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/users_controller.rb
  app/models/user_context.rb
  app/policies/application_policy.rb
  app/policies/history_policy.rb
  app/policies/monument_policy.rb
  test/policies/history_policy_test.rb
  test/policies/monument_policy_test.rb
Labels: waiting for review

#177 Alert backend and javascript ready
  app/assets/stylesheets/components/_achievement.scss
  app/assets/stylesheets/components/_index.scss
  app/controllers/histories_controller.rb
  app/javascript/controllers/achievement_controller.js
  app/javascript/controllers/index.js
  app/models/user.rb
  app/views/histories/components/achievement_alert.html.erb
  app/views/histories/show.html.erb
  db/migrate/20230326165437_add_notified_to_user_achievement.rb
  db/schema.rb
  db/seeds.rb
Labels: waiting for review

#184 Added progres logic for tourist and sprinter achievement
  app/models/user_achievement.rb
  db/seeds.rb
Labels: waiting for review

#186 Fixed some minor bugs
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/config/_setup.scss
  app/assets/stylesheets/monuments/_show.scss
Labels: waiting for review

#188 Fixed a few more stuffs
  app/assets/stylesheets/components/_flash.scss
  app/assets/stylesheets/histories/_index.scss
  app/assets/stylesheets/monuments/_show.scss
  app/assets/stylesheets/users/_dashboard.scss
  app/controllers/registrations_controller.rb
  app/javascript/controllers/flashes_controller.js
  app/javascript/controllers/glass_container_controller.js
  app/views/pages/home.html.erb
  app/views/shared/_flashes.html.erb
  app/views/users/dashboard.html.erb
Labels: waiting for review

#121 Nearby v3
  app/assets/images/location_pin.png
  app/assets/images/user-arrow.png
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/monuments/_index.scss
  app/controllers/monuments_controller.rb
  app/javascript/controllers/map_controller.js
  app/views/monuments/_card_index.html.erb
  app/views/monuments/index.html.erb
Labels: requires changes

#183 Generated UserFavouriteMonument model
  app/controllers/favourites_controller.rb
  app/models/favourite.rb
  app/models/monument.rb
  app/models/user.rb
  app/views/favourites/components/_list.html.erb
  app/views/favourites/index.html.erb
  config/routes.rb
  db/migrate/20230326202225_create_favourites.rb
  db/schema.rb
  test/controllers/favourites_controller_test.rb
  test/models/favourite_test.rb
Labels: requires changes

#176 seeded achievements
  app/assets/images/achievements/1 scan.svg
  app/assets/images/achievements/10 countries.svg
  app/assets/images/achievements/10 scan.svg
  app/assets/images/achievements/100 scan.svg
  app/assets/images/achievements/25 scan.svg
  app/assets/images/achievements/5 a day.svg
  app/assets/images/achievements/50 scan.svg
  app/assets/images/achievements/BRAZIL.svg
  app/assets/images/achievements/FRANCE.svg
  app/assets/images/achievements/PORTUGAL.svg
  app/assets/images/achievements/amsterdam.svg
  app/assets/images/achievements/belgium.svg
  app/assets/images/achievements/brussels.svg
  app/assets/images/achievements/lisbon.svg
  app/assets/images/achievements/netherlands.svg
  app/assets/images/achievements/paris.svg
  app/assets/images/achievements/rio de janeiro.svg
  db/seeds.rb
Labels: waiting for review

#190 JS CSS and Cloudinary Tweaks
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/histories/_index.scss
  app/assets/stylesheets/monuments/_index.scss
  app/javascript/controllers/block_body_scroll_controller.js
  app/javascript/controllers/glass_container_controller.js
  app/javascript/controllers/hide_home_controller.js
  app/javascript/controllers/home_logo_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/map_controller.js
  app/javascript/controllers/tutorial_controller.js
  app/views/devise/registrations/edit.html.erb
  app/views/histories/components/_list.html.erb
  app/views/histories/index.html.erb
  app/views/monuments/_card_index.html.erb
  app/views/monuments/index.html.erb
  app/views/pages/components/_logo.html.erb
  app/views/pages/components/_search_list.html.erb
  app/views/pages/components/_tutorial.html.erb
  app/views/shared/_show.html.erb
  app/views/users/components/_histories.html.erb
  app/views/users/dashboard.html.erb
Labels: waiting for review

#193 index page adapted from the historie to manteind the same design and …
  app/views/favourites/components/_list.html.erb
  app/views/favourites/index.html.erb
Labels: waiting for review

#199 Favourite
  app/assets/stylesheets/components/_button.scss
  app/controllers/favourites_controller.rb
  app/controllers/histories_controller.rb
  app/controllers/monuments_controller.rb
  app/controllers/users_controller.rb
  app/models/favourite.rb
  app/models/monument.rb
  app/models/user.rb
  app/views/favourites/components/_list.html.erb
  app/views/favourites/index.html.erb
  app/views/shared/_show.html.erb
  app/views/users/components/_favourites.html.erb
  app/views/users/dashboard.html.erb
  config/routes.rb
  db/migrate/20230326202225_create_favourites.rb
  db/schema.rb
  test/controllers/favourites_controller_test.rb
  test/models/favourite_test.rb
Labels: waiting for review
